openapi: 3.0.0
info:
  title: Data Science Models API
  version: 1.0.0
paths:
  /predict/model1:
    post:
      summary: Predict using Model 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelInput'
      responses:
        '200':
          description: Prediction result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelOutput'
components:
  schemas:
    ModelInput:
      type: object
      properties:
        feature1:
          type: number
        feature2:
          type: number
    ModelOutput:
      type: object
      properties:
        prediction:
          type: number
